POST http://localhost:3003/user
Content-Type: application/json

{
    "name": "",
    "email": "",
    "password": ""

}

###

GET http://localhost:3003/all
Content-Type: application/json

###

DELETE http://localhost:3003/:id
Content-Type: application/json